### ISSUE TITLE
Only Cropped Image has to save in database

### ISSUE THREAD

**Issue by PradeepN93** [noam148/yii2-image-manager#13]
Hi noam148,
Iam used your plugin and it is nice.

I want  only cropped images has  save in to database , but in your plugin the both cropped image and uploaded image is saving to the database.

Please help me to solve this problem...

**Comment by noam148** [comment]
@PradeepN93 At the moment there is option to keep only the cropped image. 
Unfortunately, I'm busy at the moment and there are still some other issues open.
But I will add this on my todo list for future modifications. Unfortunately I can't say when this is done but thanks for your feedback.

**Comment by bvanleeuwen1995** [comment]
@noam148 please look at PR-26

**Comment by noam148** [comment]
Please update to last release and add the next line to your imageManager module config

```
'modules' => [
	'imagemanager' => [
		'class' => 'noam148\imagemanager\Module',
		'deleteOriginalAfterEdit' => true, // false: keep original image after edit. true: delete original image after edit
	]
]
```


@PradeepN93  thanks for reporting, @bvanleeuwen1995 thanks for fixing!

**Comment by PradeepN93** [comment]
Thank You @noam148 and @bvanleeuwen1995
