### ISSUE TITLE
image picker popup url not working in module

### ISSUE THREAD

**Issue by thakkar-roshani** [noam148/yii2-image-manager#14]
hi Noam..

Thanks for your plugin.
u save lots of time of mine.

for image picker iframe is opened in model popup. Its working fine in main directory.

But when i am using it in any module,proper path is not coming so it is giving me 404.

I have traced it.
please do change in following file
noam148\yii2-image-manager\components\ImageManagerInputWidget.php

Line no : 113
from : $sBaseUrl =  Url::to(['imagemanager/manager']);
to :     $sBaseUrl =  Url::to(['/imagemanager/manager']);

As its working fine after this change.

And again thanks for plugin. I am waiting for its update.

**Comment by noam148** [comment]
Hi @thakkar-roshani, 
Thanks for reporting this issue, there is now a new update available where the change is add.
