### ISSUE TITLE
delete image from database

### ISSUE THREAD

**Issue by thakkar-roshani** [noam148/yii2-image-manager#15]
hi Noam..

How can i delete imagemanager id from database when deleting image?

On clicking delete image,image is being detached from control but how i can remove its id from database table?

**Comment by noam148** [comment]
Hi @thakkar-roshani that's only possible in the imagemanage. When you click on a image in the image overview there show up some details on the right side in de modal. There will be also a red delete button. If you click on that button, the file will be deleted and remove from the databse.
