### ISSUE TITLE
Trigger image selection from javascript frontend

### ISSUE THREAD

**Issue by gasserol** [noam148/yii2-image-manager#20]
Hi noam148, is there any way to trigger the image selector in frontend, with javascript/jquery.. for example with a button calling your widget from server (controller action)? I'm sticking in a landingpage generator (which composes elements on frontside in browser) and I would like to access the uploaded images from your extension. I would need to have either a javascript script rendering the field with selector or a button calling it, but have absolutely no idea on how I could handle this.... any input or help will be really apreciated! Many thanks in advance, Oliver

**Comment by noam148** [comment]
Hi @gasserol, it is not clear for me what you mean. Can you explain it to me more clearly, maybe with screens or something like that?

**Comment by gasserol** [comment]
Hi noam148, thanks for replying me. I want to make a cms-similar site with drag-and-drop-Editor. 
![bildschirmfoto 2017-02-26 um 15 17 43](https://cloud.githubusercontent.com/assets/4066878/23340511/c431573c-fc37-11e6-9313-68bcc40b8549.png)

on the Clientside everything is jQuery. 

On click of the upper button labeled "Change Photo" it opens fileupload from Desktop and when doing it, it sets the image in a hidden form field (input type=file):

![bildschirmfoto 2017-02-26 um 15 29 42](https://cloud.githubusercontent.com/assets/4066878/23340545/7b16c5ae-fc38-11e6-95fe-015f0da8a179.png)

on bottom is a button which I use to open already imagemanager/manager/index via a view form rendered by an action in controller.  

This is my jquery code to open it:

```
var photoNoam = form.find('#photo-noam');
            photoNoam.on('click', function(e)
                {
                    e.preventDefault();
                    var page = "http://localhost/visioMarketing3/backend/web/index.php?r=visioeditor/lpage/noamform";
                    //var page = "http://localhost/visioMarketing3/backend/web/index.php?r=imagemanager/manager&view-mode=iframe";

                    //var $dialog = $('<div></div>')
                    var $dialog = $('<div>noamdial</div>')
                        .html('<iframe style="border: 0px; " src="' + page + '" width="100%" height="100%"></iframe>')
                        .dialog({
                            dialogClass: "visioeditornoam",
                            autoOpen: false,
                            modal: true,
                            height: 700,
                            width: 1400,
                            title: "Noam ImageManager",
                            position: { my: "center", at: "center", of: window }
                        });
                    $dialog.dialog('open');


                }
            );
```


The question is: do you have any idea on how I could render the input field of your widget directly in jQuery not to have to pass over various modals? I would like to get the path of the selected image in imagemanager directly in a input field and then with jquery update the image (as it is done with the normal file uploader from desktop. Many thanks for your precious help, Oliver

**Comment by noam148** [comment]
Hi Oliver, 
So if i'm correct you want the follow:

- On click "change photo": select a photo with the file upload browser and do a file post to ?r=imagemanager/manager/upload 

- On click "photo noam": open imagemanager module and select a photo. And after select a photo, you want get the full image path back?

If this is what you want, I thick with some tricks it's possible. If you confirm this I can send you some instructions for how to. 

One question, does the file upload work already or do you want also instructions for that? 

Sorry for my late response, i'm very busy at the moment.

**Comment by gasserol** [comment]
Hi noam148, thansk for your replying. First point is absolutely correct, this is what I would realize. Second point is also correct. I can open your imagemanager module in modal, this works, but when selecting a photo only its thumbnail path is given back, not the original file path stored in db.. and another 'ugly' thing is that if you open this in modal, then the imagemanager shows up, but image selection is in modal again, somehow modal inside modal .. if this could be bypassed without to have to modify too much you code, this would be very good.. 

By the way, if your time is too short for this for the moment, I'm working on other parts of my software, so please do not hurry on my request :-) Many thanks for your precious help.

**Comment by noam148** [comment]
Hi @gasserol,

Sorry for my late respone but finally I have some time again, and as I promised i searching for a solution see:
[https://github.com/noam148/yii2-image-manager/files/949950/example.zip](https://github.com/noam148/yii2-image-manager/files/949950/example.zip)

I have test the code and everything work fine here. It's a stand alone site and it needs only:
- jquery
- Bootstrap
- Bootstrap-file input (https://github.com/kartik-v/bootstrap-fileinput)

Luckily there was no need to modify the code of the yii2-image-manager.

You can download the zip file and test the code. let me know if there any questions!

**Comment by gasserol** [comment]
Thanks @noam148 I will tryout this as soon as I have a little time, actually we have lots of customer work to do :-) many thanks anyway, I really appreciate. Will let you know. BR, Oliver

**Comment by noam148** [comment]
@gasserol please, re-open it, if you have any questions or need more help.
