### ISSUE TITLE
Dynamic form attribute

### ISSUE THREAD

**Issue by gfericsanjr** [noam148/yii2-image-manager#22]
Hi,

I work with dynamic form. My form field is:

`<?=
            $form->field($model, "[$i]image")->widget(\noam148\imagemanager\components\ImageManagerInputWidget::className(), [
                'aspectRatio' => (16 / 9),
                'showPreview' => true,
                'showDeletePickedImageConfirm' => false,
            ]);
            ?>`

This code is wrong. Getting unknown property ...:[0]image.

I think in the ImageManagerInputWidget in the 67th row, the attribute should be {Html::getAttributeName($this->attribute)} instead of {$this->attribute}).

**Comment by bvanleeuwen1995** [comment]
@noam148 I can confirm that this is a fix for the problem, but much better that I put in place a couple of weeks ago for a project.

Could you please create a PR for this fix?

**Comment by noam148** [comment]
@gfericsanjr thanks for reporting. I know there is an issue for dynamic forms. Next sunday i got time to take a look to your solution. I let you now if it's fixed!

**Comment by noam148** [comment]
Issue is fixed in release [1.2.2](https://github.com/noam148/yii2-image-manager/releases/tag/1.2.2)

Thanks again @gfericsanjr
