### ISSUE TITLE
migration table name is invalid if db has a tablePrefix

### ISSUE THREAD

**Issue by hbhe** [noam148/yii2-image-manager#23]
the migration table name may be {{%migration}}

Module.php
$mRecordMigrationRun = Yii::$app->db->createCommand('SELECT * FROM `migration` WHERE `version` = \'m170223_113221_addBlameableBehavior\'')->queryOne();

**Comment by bvanleeuwen1995** [comment]
Thank you for your report, I have just looked into this. 

We will update this is in the next release of the image manager.

**Comment by bvanleeuwen1995** [comment]
Pull request has been created
@noam148: This issue can be closed after merge.

**Comment by noam148** [comment]
Please update to last release
@hbhe thanks for reporting, @bvanleeuwen1995 thanks for fixing!
