### ISSUE TITLE
Use separate folders for each user

### ISSUE THREAD

**Issue by meverikxp** [noam148/yii2-image-manager#33]
Hi, I want make some gallery for each user on site. So I want every user need to have owner folder for uploading. But every user see all images now. Can I set folder for every user for uploading images? Thank you.

**Comment by bvanleeuwen1995** [comment]
It is currently not possible to store the images for all of the users in a separate folder, you can however enable the blameable behavior by upgrading to the latest version and set the variable 'setBlameableBehavior' to true in the module configuration (this variable can store a callable function, just return a boolean).

When enabling blameable behavior the images that are assigned to the current user will only be displayed, they can also only manage their own images thus given the illusion of the folder system.

**Comment by noam148** [comment]
Re-open it, if you have any questions
