### ISSUE TITLE
wrong Italian translation

### ISSUE THREAD

**Issue by xenogenesi** [noam148/yii2-image-manager#38]
'Cancel' => 'Cancellre', //wrong

beside an 'a' is missing should be

     'Cancel' => 'Annulla', // correct

*Cancellare* mean erase/remove/delete and is correct used in the delete translation but wrong/ambiguous for the cancel button, please use *Annulla*.

**Comment by xenogenesi** [comment]
see https://github.com/xenogenesi/yii2-image-manager/commit/a0bb85c8523c8cfbcb3e75be1561e47598b72e21

**Comment by noam148** [comment]
Sorry for my late response but thanks for the right translation
