### ISSUE TITLE
German translation of your module

### ISSUE THREAD

**Issue by gasserol** [noam148/yii2-image-manager#4]
Hi @noam148 , this would be the German translation of your module:

```
<?php
return [
    'Are you sure you want to delete this image?' => 'Wollen Sie dieses Bild wirklich löschen?',
    'Are you sure you want to detach the image?' => 'Wollen Sie dieses Bild wirklich lösen?',
    'Cancel' => 'Annullieren',
    'Created' => 'Erstellt',
    'Crop' => 'Zuschneiden',
    'Delete' => 'Löschen',
    'File hash' => 'File hash',
    'File name' => 'File Name',
    'Modified' => 'Geändert',
    'Search' => 'Suchen',
    'Select' => 'Auswählen',
];
```

this is the french version:

```
<?php
return [
    'Are you sure you want to delete this image?' => 'Voulez-vous vraiment effacer cet'image?',
    'Are you sure you want to detach the image?' => 'Voules-vous détacher cet'image?',
    'Cancel' => 'Annuler',
    'Created' => 'Crée',
    'Crop' => 'Ajuster',
    'Delete' => 'Effacer',
    'File hash' => 'Hash du fichier',
    'File name' => 'Nom du fichier',
    'Modified' => 'Modifié',
    'Search' => 'Rechercher',
    'Select' => 'Sélectionner',
];

```

and this is the italian version:

<?php
return [
    'Are you sure you want to delete this image?' => 'Vuole veramente cancellare questa immagine?',
    'Are you sure you want to detach the image?' => 'Vuole distaccare questa immagine?',
    'Cancel' => 'Cancellre',
    'Created' => 'Creato',
    'Crop' => 'Tagliare a formato',
    'Delete' => 'Cancellare',
    'File hash' => 'File hash',
    'File name' => 'Nome del file',
    'Modified' => 'Modificato',
    'Search' => 'Ricerca',
    'Select' => 'Selezionare',
];

Hope this might help for internationalization :-) Best regards and many thanks!

**Comment by noam148** [comment]
Thanks @gasserol, the translations are added!
