### ISSUE TITLE
How to upload files at root of yii2 advance

### ISSUE THREAD

**Issue by faisalijaz** [noam148/yii2-image-manager#41]
I am trying to configure it for the root of document but its not working I have created a config as it was told,

` 'imagemanager' => [
            'class' => 'noam148\imagemanager\components\ImageManagerGetPath',
            //set media path (outside the web folder is possible)
            'mediaPath' => '/uploads',
            //path relative web folder to store the cache images
            'cachePath' => 'assets/images',
            //use filename (seo friendly) for resized images else use a hash
            'useFilename' => true,
            //show full url (for example in case of a API)
            'absoluteUrl' => false,
            'databaseComponent' => 'db' // The used database component by the image manager, this defaults to the Yii::$app->db component
        ],`

**and error i am getting is:**

> {"name":"Exception","message":"Failed to create directory \"/uploads\": mkdir(): Permission denied","code":2,"type":"yii\\base\\Exception","file":"/opt/lampp/htdocs/new_bbg/vendor/yiisoft/yii2/helpers/BaseFileHelper.php","line":559,"stack-trace":["#0 /opt/lampp/htdocs/new_bbg/vendor/noam148/yii2-image-manager/controllers/ManagerController.php(134): yii\\helpers\\BaseFileHelper::createDirectory('/uploads')","#1 [internal function]: noam148\\imagemanager\\controllers\\ManagerController->actionUpload()","#2 /opt/lampp/htdocs/new_bbg/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)","#3 /opt/lampp/htdocs/new_bbg/vendor/yiisoft/yii2/base/Controller.php(157): yii\\base\\InlineAction->runWithParams(Array)","#4 /opt/lampp/htdocs/new_bbg/vendor/yiisoft/yii2/base/Module.php(528): yii\\base\\Controller->runAction('upload', Array)","#5 /opt/lampp/htdocs/new_bbg/vendor/yiisoft/yii2/web/Application.php(103): yii\\base\\Module->runAction('imagemanager/ma...', Array)","#6 /opt/lampp/htdocs/new_bbg/vendor/yiisoft/yii2/base/Application.php(386): yii\\web\\Application->handleRequest(Object(yii\\web\\Request))","#7 /opt/lampp/htdocs/new_bbg/backend/web/index.php(17): yii\\base\\Application->run()","#8 {main}"],"previous":{"name":"PHP Warning","message":"mkdir(): Permission denied","code":2,"type":"yii\\base\\ErrorException","file":"/opt/lampp/htdocs/new_bbg/vendor/yiisoft/yii2/helpers/BaseFileHelper.php","line":554,"stack-trace":["#0 [internal function]: yii\\base\\ErrorHandler->handleError(2, 'mkdir(): Permis...', '/opt/lampp/htdo...', 554, Array)","#1 /opt/lampp/htdocs/new_bbg/vendor/yiisoft/yii2/helpers/BaseFileHelper.php(554): mkdir('/uploads', 509)","#2 /opt/lampp/htdocs/new_bbg/vendor/noam148/yii2-image-manager/controllers/ManagerController.php(134): yii\\helpers\\BaseFileHelper::createDirectory('/uploads')","#3 [internal function]: noam148\\imagemanager\\controllers\\ManagerController->actionUpload()","#4 /opt/lampp/htdocs/new_bbg/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)","#5 /opt/lampp/htdocs/new_bbg/vendor/yiisoft/yii2/base/Controller.php(157): yii\\base\\InlineAction->runWithParams(Array)","#6 /opt/lampp/htdocs/new_bbg/vendor/yiisoft/yii2/base/Module.php(528): yii\\base\\Controller->runAction('upload', Array)","#7 /opt/lampp/htdocs/new_bbg/vendor/yiisoft/yii2/web/Application.php(103): yii\\base\\Module->runAction('imagemanager/ma...', Array)","#8 /opt/lampp/htdocs/new_bbg/vendor/yiisoft/yii2/base/Application.php(386): yii\\web\\Application->handleRequest(Object(yii\\web\\Request))","#9 /opt/lampp/htdocs/new_bbg/backend/web/index.php(17): yii\\base\\Application->run()","#10 {main}"]}}

**Comment by agendy** [comment]
I added the below and works properly with me
in component
'imagemanager' => [
            'class' => 'noam148\imagemanager\components\ImageManagerGetPath',
            //set media path (outside the web folder is possible)
            'mediaPath' => dirname(dirname(__DIR__)) . '/frontend/web/manual/images/uploads/media',
            //path relative web folder to store the cache images
            'cachePath' =>'manual/images/uploads/cache',
            //use filename (seo friendly) for resized images else use a hash
            'useFilename' => true,
            //show full url (for example in case of a API)
            'absoluteUrl' => TRUE,
            'databaseComponent' => 'db' // The used database component by the image manager, this defaults to the Yii::$app->db component
        ],
notify to duplicate cach file in both backend and frontend

**Comment by bvanleeuwen1995** [comment]
With your first config example, the /upload was expecting to upload the files to the root of your disk in de upload folder, this will always give a array unless special permission is given to write to this location.

What I recommend your to do is use the Yii::getAlias() function, this will automatically build the correct location path. It is what I always use.

**Comment by noam148** [comment]
Do you have still this issue? Please re-open issue
