### ISSUE TITLE
500 (Internal Server Error)

### ISSUE THREAD

**Issue by olena-melnik** [noam148/yii2-image-manager#60]
Hello, when loading your application an error occurs
![Screenshot_3](https://user-images.githubusercontent.com/27019451/56095680-ed1bf700-5ee7-11e9-8862-910f5582d2eb.png)

**Comment by olena-melnik** [comment]
![image](https://user-images.githubusercontent.com/27019451/56467699-2e059580-642b-11e9-882b-7570205c144d.png)

**Comment by pvolyntsev** [comment]
@olena-melnik Please provide with details from Yii application error log

**Comment by olena-melnik** [comment]
![image](https://user-images.githubusercontent.com/27019451/57724254-0c4aa780-7693-11e9-8395-41f870993de3.png)

**Comment by olena-melnik** [comment]
@pvolyntsev 
![image](https://user-images.githubusercontent.com/27019451/57724299-271d1c00-7693-11e9-95de-254978174ea4.png)

**Comment by olena-melnik** [comment]
@pvolyntsev 
![image](https://user-images.githubusercontent.com/27019451/57724334-3dc37300-7693-11e9-8e8b-2d3c038f44d3.png)

**Comment by olena-melnik** [comment]
@pvolyntsev 
Thank you, I didn`t even hope for an answer.

**Comment by pvolyntsev** [comment]
@olena-melnik I see you didn't change sample configuration options

This option
```'mediaPath' => '/path/where/to/store/images/media/imagemanager',```
shoud be set according to your case

**Comment by olena-melnik** [comment]
Thank you very much)) "I noticed not the elephant at all"
