### ISSUE TITLE
Crop and select combination button

### ISSUE THREAD

**Issue by bvanleeuwen1995** [noam148/yii2-image-manager#7]
Would it be possible to add a crop and select button, what currently happen is that I choose a image and crop it the way I want it to be. When I'm done I click on the select button, but the non-cropped version gets selected, and the cropped image is not save.

Would it be possible to combine the current select button to also save the cropped image, and automatically select it?

Ore if you reckon this is impractical/confusing, add a button underneath it for this specific functions? Must of the time, when I upload a image, then crop it, I miss the two buttons under the image completely. This is where this 'problem' comes from, I automatically look for control button in the right bottom corner of a page/modal.

**Comment by noam148** [comment]
I work on it after the next weekend

**Comment by noam148** [comment]
Add the button in the last release, don't forget to clear the assets cache!
